### PR TITLE
Enable nullability and trimming

### PR DESCRIPTION
**Pull request by neon-sunset**
This is a small change to explicitly enable nullable (in addition to existing attributes) and trimming.

Also, https://github.com/VSadov/NonBlocking/blob/master/src/NonBlocking/ConcurrentDictionary/ConcurrentDictionary.cs#L154 produces an AOT warning so I'm going to look whether it is fixable later on - will submit a PR once (hopefully) fixed.

### CODE REVIEW

**Comment by VSadov** [comment]
I am concerned that linker may consider `CreateRef` unused based on the static analysis and remove it.

Is it possible to root `CreateRef` as described in https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options#root-descriptors ?

**Comment by neon-sunset** [comment]
Thanks for linking up the documentation, my knowledge on trimming and/or AOT is still scarce 😅.
Rooted `CreateRef` as requested.

A couple of findings:
1. Trimmed self-contained applications that access `CreateRefUnsafe` work properly regardless if descriptor is present.
2. Native AOT is unfortunately broken for `TKey : class` because `CreateRefUnsafe` fails with `EETypeRva:0x0049BAD8: MakeGenericMethod() cannot create this generic method instantiation because no code was generated for it`.

After looking into implementations of both BCLs `ConcurrentDictionary` and the version of this library intended for merge in https://github.com/dotnet/runtime/pull/50337, it appears the difference is that specialized `DictionaryImplRef` is not constrained to `class`. I assume the main reason to introduce it here was either better codegen or some low-level gotcha.

**Comment by VSadov** [comment]
> Native AOT is unfortunately broken for TKey : class because CreateRefUnsafe fails with EETypeRva:0x0049BAD8: MakeGenericMethod() cannot create this generic method instantiation because no code was generated for it.

@MichalStrehovsky - could you take a look? Is this a bug in AOT or we need to do something to make the code more trimming-friendly?
It is a fairly simple pattern. There is nothing truly dynamic, The goal is basically just to get around the `as class` constraint when constructing an instance. We know `TKey` is a reference type, but can't express that statically in C#.

https://github.com/VSadov/NonBlocking/blob/1ac8d8564cb0a7894fad2b00f40d590017ff6555/src/NonBlocking/ConcurrentDictionary/ConcurrentDictionary.cs#L150

**Comment by MichalStrehovsky** [comment]
> I am concerned that linker may consider CreateRef unused based on the static analysis and remove it.

Static analysis will generate a warning if there's a problem recognizing a reflection pattern in the app. If there is such problem:

* There will be a warning from the Roslyn analyzer when building this project because setting `IsTrimmable` to true enabled a trimming Roslyn analyzer.
* The user will also get a warning when trying to use the library with trimming.

One only needs to use the XML when the static analysis can't figure something out and there's a warning. In addition to writing the XML, one also needs to put a suppression in place or users of the library will keep getting warnings about the pattern.

In this case, the reflection pattern is 100% statically analyzable and XML or suppression is not needed:

https://github.com/VSadov/NonBlocking/blob/393675f0b7fa8e4a05dc88e1c3f6f09de164e8e6/src/NonBlocking/ConcurrentDictionary/ConcurrentDictionary.cs#L153-L154

I wish we didn't even document the XML. It just confuses people. Delete the file and forget the mechanism exists. No warnings means no problems.

> @MichalStrehovsky - could you take a look? Is this a bug in AOT or we need to do something to make the code more trimming-friendly?

MakeGenericMethod is [annotated as not AOT friendly](https://github.com/dotnet/runtime/blob/d85ec4ee22deaeaabf8389ad492e28be8305f935/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Reflection/Emit/MethodBuilder.cs#L213), generates warnings at AOT build (and from AOT analyzer in .NET 7), and tends to not work at runtime. It's unrelated to trimming. MakeGenericMethod is usually [runtime codegen](https://twitter.com/MStrehovsky/status/1244602445461950470). NativeAOT can make it work if we have code available, but the dynamic nature of it means that most of the time we don't.

**Comment by neon-sunset** [comment]
@MichalStrehovsky @VSadov 
Thanks, reverted the ILLink descriptors change. As for NAOT and `MakeGenericMethod` - it is as described, the code is unavailable during runtime.

However, theoretically speaking, `CreateRefUnsafe`/`CreateRef` should be fully expressible in IL to call the necessary impl directly, given that we always guarantee the constraint `TKey : class` is satisfied.

I'm aware the runtime itself does use IL stubs in some scenarios but don't know how one could achieve so in a third-party library. If you have any documentation on this - please let me know!

**Comment by VSadov** [comment]
I think I can get rid of `MakeGenericMethod`

**Comment by VSadov** [comment]
Get rid of MakeGenericMethod: https://github.com/VSadov/NonBlocking/pull/15

**Comment by neon-sunset** [comment]
@VSadov Nice, thank you!
As for this PR and #14, is there anything else that needs to be fixed to get them merged?

P.S.: just noticed there may also be an optimization opportunity for unmanaged comparer-less structs that aren't primitives by reinterpreting them as int/nint and using corresponding underlying implementation aka `Unsafe.As<(int, byte, bool), nint>(ref key)`

**Comment by VSadov** [comment]
> As for this PR and https://github.com/VSadov/NonBlocking/pull/14, is there anything else that needs to be fixed to get them merged?

I was not sure if you wanted to retry the AOT scenario, but I think the issue should be fixed and this can be merged.

**Comment by VSadov** [comment]
> optimization opportunity for unmanaged comparer-less structs that aren't primitives by reinterpreting them as int/nint 

It is possible, but is it a common enough case?
Most uses that I see use strings or integers as keys. Other kinds of keys seem rare.

**Comment by neon-sunset** [comment]
> I was not sure if you wanted to retry the AOT scenario, but I think the issue should be fixed and this can be merged.

Yes, Native AOT no longer crashes with `master`, no warnings produced either.

**Comment by VSadov** [comment]
I will merge this then. Thank you!!

**Pull request merged**
